
#ifndef CONSTANTS_INCLUDED
#define CONSTANTS_INCLUDED

#define SOFT_AP_SSID "ESP32 SoftAP"
#define SOFT_AP_PASSWORD "password"

#define SOFT_AP_IP_ADDRESS_1 192
#define SOFT_AP_IP_ADDRESS_2 168
#define SOFT_AP_IP_ADDRESS_3 5
#define SOFT_AP_IP_ADDRESS_4 18

#define SOFT_AP_GW_ADDRESS_1 192
#define SOFT_AP_GW_ADDRESS_2 168
#define SOFT_AP_GW_ADDRESS_3 5
#define SOFT_AP_GW_ADDRESS_4 20

#define SOFT_AP_NM_ADDRESS_1 255
#define SOFT_AP_NM_ADDRESS_2 255
#define SOFT_AP_NM_ADDRESS_3 255
#define SOFT_AP_NM_ADDRESS_4 0
#define HTTPD_RESP_USE_STRLEN -1

#define SERVER_PORT 3500

// pins
#define GPIO_OUTPUT_IO_2 2

#define GPIO_OUTPUT_PIN_SEL \
    ((1ULL << GPIO_OUTPUT_IO_2))

#endif